[package]
name = "base_rt"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core.workspace = true

cpu_timer.workspace = true

tokio.workspace = true
once_cell.workspace = true
tracing.workspace = true
tokio-util = { workspace = true, features = ["rt"] }
