[package]
name = "sb_event_worker"
version = "0.1.0"
authors = ["Supabase <team@supabase.com>"]
edition = "2021"
license = "MIT"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true

base_mem_check.workspace =  true

uuid.workspace = true
serde.workspace = true
anyhow.workspace = true
tokio.workspace = true
log.workspace = true
tracing.workspace = true
enum-as-inner.workspace = true

[features]
tracing = []