# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "sb_node"
version = "0.1.0"
authors = ["Supabase <team@supabase.com>"]
edition = "2021"
license = "MIT"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_fetch.workspace = true
deno_fs.workspace = true
deno_media_type.workspace = true
deno_net.workspace = true
deno_config = { workspace = true, default-features = false, features = ["package_json"] }
deno_whoami = "0.1.0"

libc.workspace = true
http.workspace = true
libz-sys.workspace = true
tokio.workspace = true
async-trait.workspace = true
once_cell.workspace = true
nix.workspace = true
num-bigint.workspace = true
bytes.workspace = true
faster-hex.workspace = true
indexmap.workspace = true
regex.workspace = true
reqwest.workspace = true
ring.workspace = true
rsa.workspace = true
url.workspace = true
aes.workspace = true
brotli.workspace = true
cbc.workspace = true
ecb.workspace = true
data-encoding.workspace = true
elliptic-curve.workspace = true
hkdf.workspace = true
http_v02.workspace = true
lazy-regex.workspace = true
p224.workspace = true
p256.workspace = true
p384.workspace = true
sha1.workspace = true
sha2.workspace = true
rand.workspace = true
signature.workspace = true
spki.workspace = true
winapi.workspace = true
h2.workspace = true
thiserror.workspace = true

aead-gcm-stream = "0.1"
const-oid = "0.9.5"
digest = { version = "0.10.5", features = ["core-api", "std"] }
dsa = "0.6.1"
errno = "0.2.8"
idna = "0.3.0"
k256 = "0.13.1"
md-5 = { version = "0.10.5", features = ["oid"] }
md4 = "0.10.2"
num-bigint-dig = "0.8.2"
num-integer = "0.1.45"
num-traits = "0.2.14"
path-clean = "=0.1.0"
pbkdf2 = "0.12.1"
pin-project-lite = "0.2.13"
ripemd = { version = "0.1.3", features = ["oid"] }
scrypt = "0.11.0"
sec1 = "0.7"
serde = "1.0.149"
sha3 = { version = "0.10.8", features = ["oid"] }
blake2 = "0.10.6"
sm3 = "0.4.2"
simd-json = "0.13.4"
x25519-dalek = "2.0.0"
x509-parser = "0.15.0"
ipnetwork = "0.20.0"

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
winapi = { workspace = true, features = ["consoleapi"] }
