# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "ext_node"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true

deno_fetch.workspace = true
deno_fs.workspace = true
deno_io.workspace = true
deno_net.workspace = true
deno_package_json.workspace = true
deno_path_util.workspace = true
deno_permissions.workspace = true

node_resolver.workspace = true

aes.workspace = true
base64.workspace = true
brotli.workspace = true
bytes.workspace = true
cbc.workspace = true
data-encoding.workspace = true
ecb.workspace = true
elliptic-curve.workspace = true
faster-hex.workspace = true
h2.workspace = true
hkdf.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
libc.workspace = true
libz-sys.workspace = true
num-bigint.workspace = true
once_cell.workspace = true
p224.workspace = true
p256.workspace = true
p384.workspace = true
rand.workspace = true
ring.workspace = true
rsa.workspace = true
sec1.workspace = true
serde.workspace = true
sha1.workspace = true
sha2.workspace = true
spki.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
webpki-root-certs.workspace = true
winapi.workspace = true
yoke.workspace = true

aead-gcm-stream = "0.3"
blake2 = "0.10.6"
boxed_error = "0.2.2"
const-oid = "0.9.5"
deno_whoami = "0.1.0"
der = { version = "0.7.9", features = ["derive"] }
digest = { version = "0.10.5", features = ["core-api", "std"] }
dsa = "0.6.3"
ecdsa = "0.16.9"
ed25519-dalek = { version = "2.1.1", features = ["digest", "pkcs8", "rand_core", "signature"] }
errno = "0.2.8"
home = "0.5.9"
idna = "1.0.3"
ipnetwork = "0.20.0"
k256 = "0.13.1"
md-5 = { version = "0.10.5", features = ["oid"] }
md4 = "0.10.2"
memchr = "2.7.4"
num-bigint-dig = "0.8.2"
num-integer = "0.1.45"
num-traits = "0.2.14"
pbkdf2 = "0.12.1"
pin-project-lite = "0.2.13"
pkcs8 = { version = "0.10.2", features = ["std", "pkcs5", "encryption"] }
ripemd = { version = "0.1.3", features = ["oid"] }
scrypt = "0.11.0"
sha3 = { version = "0.10.8", features = ["oid"] }
simd-json = "0.14.0"
sm3 = "0.4.2"
tokio-eld = "0.2"
x25519-dalek = { version = "2.0.0", features = ["static_secrets"] }
x509-parser = "0.15.0"

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
winapi = { workspace = true, features = ["consoleapi"] }
