[package]
name = "sb_npm"
version = "0.1.0"
authors = ["Supabase <team@supabase.com>"]
edition = "2021"
resolver = "2"
description = "We'll take care of this later"
license = "MIT"

[lib]
path = "lib.rs"

[dependencies]
deno_ast.workspace = true
deno_core.workspace = true
deno_npm.workspace = true
deno_fs.workspace = true
deno_semver.workspace = true
once_cell.workspace = true
async-trait.workspace = true
base32 = "=0.4.0"
deno_lockfile.workspace = true
tar.workspace = true
flate2.workspace = true
ring.workspace = true
sb_node = { version = "0.1.0", path = "../node" }
sb_core = { version = "0.1.0", path = "../sb_core" }
serde.workspace = true
percent-encoding = "=2.3.0"
hex = "0.4"
base64.workspace = true
bincode = "=1.3.3"
thiserror.workspace = true